/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multDivSelect.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1e09fcfd742d5013f3136d7f161308ee)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sdrSmoke/multDivSelect.h>
// pydoc.h is automatically generated in the build directory
#include <multDivSelect_pydoc.h>

void bind_multDivSelect(py::module& m)
{

    using multDivSelect    = gr::sdrSmoke::multDivSelect;


    py::class_<multDivSelect, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<multDivSelect>>(m, "multDivSelect", D(multDivSelect))

        .def(py::init(&multDivSelect::make),
           D(multDivSelect,make)
        )
        



        ;




}








